### PR TITLE
#161 update macs calibration library

### PR DESCRIPTION
**Pull request by deepkyu**
## Description

Please include a summary in English, of the changes in this pull request. If it closes an issue, please mention it here.

Closes: #161

You should link at least one existing issue for PR. Before your create a PR, please check to see if there is an issue for this change.  
PRs from forked repository not accepted.

## Change(s)

- Synchronize MACs calibration library with PyNetsPresso and NetsPresso platform
  - https://docs.netspresso.ai/docs/release-notes

## Changelog

If you PR to `dev` branch, please add a brief summary of the change to the **Upcoming Release** section of the [`CHANGELOG.md`](https://github.com/Nota-NetsPresso/netspresso-trainer/blob/master/CHANGELOG.md) file and include a link to the PR (formatted in markdown) and a link to your github profile.

For example,

```
- Added a new feature by `@myusername` in [PR 2023](https://github.com/Nota-NetsPresso/netspresso-trainer/pull/2023)
```

## Code Formatting

If you PR to either `master` or `dev` branch, you should follow the code linting process. Please check your code with `lint_check.sh` in `./scripts` directory.
For more information, please read the contribution guide in `CONTRIBUTING.md`.

### CODE REVIEW

**Comment by deepkyu** [comment]
Added special reviewer @Only-bottle for:
- Validate the counter update

**Comment by deepkyu** [comment]
fvcore does not separately count pooling layers and `add_` operators. This [issue](https://github.com/sovrasov/flops-counter.pytorch/issues/94) is also mentioned in the fvcore issue.

In addition, fvcore does not provide a separate count for params, so I have changed it to the commonly used one, `params = sum(p.numel() for p in model.parameters())`. This is equivalent with the caliration procedure in `thop`.
As a result, in NP Trainer ResNet50, I have confirmed the following results. Note that the params remain the same, but there is a difference in MACs.

**fvcore + vanila params count**
```
2023-10-23_06:47:31 UTC | INFO          | save_summary:<base.py>:322 >>> [Model stats] Params: 23.51M | MACs: 5.37G
```

**thop**
```
2023-10-23_06:48:32 UTC | INFO          | save_summary:<base.py>:322 >>> [Model stats] Params: 23.51M | MACs: 5.40G
```

**Review by Only-bottle — APPROVED** [review]
👍🏻

**Review by illian01 — APPROVED** [review]
LGTM!

**Pull request merged**
