### PR TITLE
168 some files are missing with pacakge installation

### PR DESCRIPTION
**Pull request by deepkyu**
## Description

Please include a summary in English, of the changes in this pull request. If it closes an issue, please mention it here.

Closes: #168

You should link at least one existing issue for PR. Before your create a PR, please check to see if there is an issue for this change.  
PRs from forked repository not accepted.

## Change(s)

- After updating subdirectory structure, I added setup in `setup.py`
- Tested with gradio demo, package import works.

## Changelog

If you PR to `dev` branch, please add a brief summary of the change to the **Upcoming Release** section of the [`CHANGELOG.md`](https://github.com/Nota-NetsPresso/netspresso-trainer/blob/master/CHANGELOG.md) file and include a link to the PR (formatted in markdown) and a link to your github profile.

For example,

```
- Added a new feature by `@myusername` in [PR 2023](https://github.com/Nota-NetsPresso/netspresso-trainer/pull/2023)
```

## Code Formatting

If you PR to either `master` or `dev` branch, you should follow the code linting process. Please check your code with `lint_check.sh` in `./scripts` directory.
For more information, please read the contribution guide in `CONTRIBUTING.md`.

### CODE REVIEW

**Review by illian01 — COMMENTED** [review]
I don't understand how the bug fixed with `package_data={"": ["VERSION"]},`.
Please can you explain how it works?

**Comment by deepkyu** [comment]
@illian01 

I tried to solve this issue with single commit (https://github.com/Nota-NetsPresso/netspresso-trainer/commit/d8b3a925c6a4b7c3c3275f9316375c8faa61d812 ), but in later found out in needs several fixes ..

**Comment by deepkyu** [comment]
@illian01 
d8b3a92 mainly solves the issue, but it was not the end.
So, I added some fixes with this branch.

**Review by illian01 — APPROVED** [review]
Oh, the commits was separated. Thank you!
LGTM!

**Pull request merged**
